[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
]
runner = "blash --port COM4 --monitor-baud 2000000 --"

[target.riscv32imafc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Thal_defaults.x",
]
runner = "blash --port COM4 --monitor-baud 2000000 --"

[build]
target = "riscv32imafc-unknown-none-elf.json"
